version: 1
formatters:
  default:
    format: "%(levelname)s %(name)s - %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    formatter: default
root:
  level: INFO
  handlers: [console]
